# Forest Flower Powerline Preset for Starship (Clean - No Empty Segments)
# Inspired by Pastel Powerline with Forest Flower's warm, nature-based palette

format = """
[](#c4a7e7)\
$username\
[](bg:#ea9a97 fg:#c4a7e7)\
$directory\
[](fg:#ea9a97 bg:#d9a85f)\
$git_branch\
$git_status\
$bun\
$nodejs\
$python\
$rust\
$golang\
$time\
$line_break\
$character\
"""

[username]
show_always = true
style_user = "bg:#c4a7e7 fg:#101010"
style_root = "bg:#c4a7e7 fg:#f85552"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#ea9a97 fg:#101010"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Code" = " "
"Developer" = " "

[git_branch]
symbol = ""
style = "bg:#d9a85f fg:#101010"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#d9a85f fg:#101010"
format = '[$all_status$ahead_behind ]($style)'

# Language modules - Only show when detected
[bun]
symbol = "🍞"
style = "bg:#89b4a8 fg:#101010"
format = '[](fg:#d9a85f bg:#89b4a8)[ $symbol ($version) ]($style)'
detect_files = ['bun.lockb', 'bunfig.toml']

[nodejs]
symbol = ""
style = "bg:#89b4a8 fg:#101010"
format = '[](fg:#d9a85f bg:#89b4a8)[ $symbol ($version) ]($style)'
detect_files = ['package.json', '.node-version', '.nvmrc']

[python]
symbol = " "
style = "bg:#89b4a8 fg:#101010"
format = '[](fg:#d9a85f bg:#89b4a8)[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#89b4a8 fg:#101010"
format = '[](fg:#d9a85f bg:#89b4a8)[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#89b4a8 fg:#101010"
format = '[](fg:#d9a85f bg:#89b4a8)[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#a67c52 fg:#e6e1cf"
format = '[](fg:#d9a85f bg:#a67c52)[ ♥ $time ]($style)[ ](fg:#a67c52)'

[character]
success_symbol = '[➜](bold #b4d494)'
error_symbol = '[➜](bold #f85552)'
