# Forest Flower Powerline Preset for Starship
# Full version with language detection
# Proper UTF-8 powerline arrows

format = """
$username\
[](bg:#d699b6 fg:#b4d494)\
$directory\
[](fg:#d699b6 bg:#7fbbb3)\
$git_branch\
$git_status\
[](fg:#7fbbb3 bg:#89b4a8)\
$bun\
$nodejs\
$python\
$rust\
$golang\
[](fg:#89b4a8 bg:#d9a85f)\
$time\
[ ](fg:#d9a85f)\
"""

[username]
show_always = true
style_user = "bg:#b4d494 fg:#101010"
style_root = "bg:#b4d494 fg:#f85552"
format = '[ $user ]($style)'
disabled = false

[directory]
style = "bg:#d699b6 fg:#101010"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Code" = " "
"Developer" = " "

[git_branch]
symbol = ""
style = "bg:#7fbbb3 fg:#101010"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#7fbbb3 fg:#101010"
format = '[$all_status$ahead_behind ]($style)'

# Language modules - show in sage segment when detected
[bun]
symbol = "🍞"
style = "bg:#89b4a8 fg:#101010"
format = '[ $symbol ($version) ]($style)'
detect_files = ['bun.lockb', 'bunfig.toml']

[nodejs]
symbol = ""
style = "bg:#89b4a8 fg:#101010"
format = '[ $symbol ($version) ]($style)'
detect_files = ['package.json', '.node-version', '.nvmrc']

[python]
symbol = " "
style = "bg:#89b4a8 fg:#101010"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#89b4a8 fg:#101010"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = " "
style = "bg:#89b4a8 fg:#101010"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#d9a85f fg:#e6e1cf"
format = '[ ♥ $time ]($style)'
