# Forest Flower Minimal Powerline for Starship
# Simple, clean, always works - no language detection

format = """
[](#c4a7e7)\
$username\
[](bg:#ea9a97 fg:#c4a7e7)\
$directory\
[](fg:#ea9a97 bg:#d9a85f)\
$git_branch\
$git_status\
[](fg:#d9a85f bg:#a67c52)\
$time\
[ ](fg:#a67c52)\
"""

[username]
show_always = true
style_user = "bg:#c4a7e7 fg:#101010"
style_root = "bg:#c4a7e7 fg:#f85552"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#ea9a97 fg:#101010"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Code" = " "
"Developer" = " "

[git_branch]
symbol = ""
style = "bg:#d9a85f fg:#101010"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#d9a85f fg:#101010"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#a67c52 fg:#e6e1cf"
format = '[ ♥ $time ]($style)'
